services:
  backend:
    build:
      context: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend-db
      - backend-frontend

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - backend-frontend

  database:
    image: postgres
    secrets:
      - db-password
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD_FILE: /run/secrets/db-password
       POSTGRES_DB: db
    healthcheck:
       test: [ "CMD-SHELL", "pg_isready -U postgres" ]
       interval: 5s
       timeout: 5s
       retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-db

volumes:
  db-data:

secrets:
  db-password:
    file: userDatabase/password.txt

networks:
  backend-frontend:
  backend-db:
