services:
  server:
    build:
      context: backend
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - backend-db
      - backend-frontend

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
      - backend-frontend

  db:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
       POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-db

volumes:
  db-data:

networks:
  backend-frontend:
  backend-db:

#  db:
#    secrets:
#      - db-password
#    environment:
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#secrets:
#  db-password:
#    file: userDatabase/password.txt
