services:
  server:
    build:
      context: backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somerootpass
      - MYSQL_DATABASE=users
      - MYSQL_PASSWORD=somepass
      - MYSQL_USER=someuser
    volumes:
      - database:/data/db
    expose:
      - 3306

volumes:
  database:

#    depends_on:
#      db:
#        condition: service_healthy
#  db:
#    image: postgres
#    restart: always
#    user: postgres
#    secrets:
#      - db-password
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=example
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#    expose:
#      - 5432
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#volumes:
#  db-data:
#secrets:
#  db-password:
#    file: userDatabase/password.txt
#
